blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='homepage')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, VerifyEmailView, ProfileView, UserListView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify_email/<str:uid>/<str:token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('users_list/', UserListView.as_view(), name='users_list'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}
ACTIVE_CHOICES = [
    (True, 'Активен'),
    (False, 'Неактивен'),
]


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    phone = models.CharField(max_length=20, verbose_name='Телефон', **NULLABLE)
    verification_token = models.CharField(max_length=100, blank=True, verbose_name='Код подтверждения почты')
    is_active = models.BooleanField(default=False, choices=ACTIVE_CHOICES, verbose_name='Почта активирована')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        # fields = '__all__'
        fields = ('email', 'first_name', 'last_name', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.utils.crypto import get_random_string
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        new_user = form.save()
        token = get_random_string(length=10)
        new_user.verification_token = token
        new_user.save()
        current_site = get_current_site(self.request)

        send_mail(
            subject='Подтверждение аккаунта',
            message=f'Поздравляем, Вы зарегистрировались на нашем портале!\n'
            f'Для завершения регистрации и подтверждения вашей электронной почты, '
            f'пожалуйста, кликните по следующей ссылке:\n'
            f'http://{current_site.domain}{reverse("users:verify_email", kwargs={"uid": new_user.pk, "token": token})}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )

        return super().form_valid(form)


class VerifyEmailView(View):
    def get(self, request, uid, token):
        try:
            user = get_object_or_404(User, pk=uid, verification_token=token)
            user.is_active = True
            user.save()
            return render(request, 'users/register_success.html')  # Покажем сообщение о регистрации
        except User.DoesNotExist:
            return render(request, 'users/register_failed.html')  # Покажем сообщение об ошибке


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserListView(LoginRequiredMixin, ListView):
    model = User
    extra_context = {'title': 'Пользователи',}

    # def test_func(self):
    #     _user = self.request.user
    #     if _user.has_perms(['users.set_is_active',]):
    #         return True
    #     return self.handle_no_permission()

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}

    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-12">
                <div class="row">
                    <div class="col-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">
                                    Вход
                                </h3>
                            </div>
                            <div class="card-body">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-primary">Войти</button>
                                <a href=#>Забыли пароль?</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-12">
                <div class="row">
                    <div class="col-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">
                                    Регистрация
                                </h3>
                            </div>
                            <div class="card-body">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-primary" href={% url 'users:register' %}>Регистрация</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/register_failed.html
{% extends 'mailing/base.html' %}

{% block content %}
    <h1>Ошибка!</h1>
    <p>Неверная ссылка подтверждения.</p>
    <a href="{% url 'catalog:index' %}">На главную страницу</a>

{% endblock %}

users/templates/users/register_success.html
{% extends 'mailing/base.html' %}

{% block content %}
    <h1>Поздравляем!</h1>
    <p>Вы успешно зарегистрировались на нашем портале.</p>
    <a href="{% url 'users:login' %}">Войти</a>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-12">
                <div class="row">
                    <div class="col-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">
                                    Профиль
                                </h3>
                            </div>
                            <div class="card-body">
                                {% csrf_token %}
                                {% if user.profile.avatar %}
                                    <div class="mb-3">
                                        <img src="{{ user.profile.avatar.url }}" alt="Аватар" class="img-fluid rounded-circle mb-3" style="max-width: 150px;">
                                    </div>
                                {% endif %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/base.html' %}
{% block content %}

    <div class="container">
        <div class="row">

            {% for object in object_list %}
                <div class="col-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h5 class="card-title">{{ object.name }}</h5>
                            <p class="card-text">E-mail: {{ object.email }}</p>
                            {% if not object.is_active %}
                                <p class="card-text">Заблокирован</p>
                            {% else %}
                                <p class="card-text">Активный</p>
                            {% endif %}

                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>

{% endblock %}